/**
 * Task C.1 — AC1 unit test: AI extraction includes DEFAULT_MICROS_LIST keys.
 *
 * Asserts the Gemini text-parse and vision system prompts both contain the
 * `micros` directive that enumerates the canonical 30 keys from
 * `lib/nutrition/micros-rda.ts::DEFAULT_MICROS_LIST`. The AI returns the
 * `micros` field as a string-to-number map (Zod stays permissive at
 * `z.record(z.string(), z.number())` per architecture spec §7.3); the
 * KEY-MEMBERSHIP invariant is enforced at this test level (Lesson #5
 * tradeoff: Zod tightness vs fixture compatibility).
 *
 * RED-1 (characterization for existing brownfield files): asserts the
 * pre-change state — current prompts do NOT enumerate the canonical 30
 * keys; current schema's `micros` is `z.record(z.string(), z.number())`.
 *
 * RED-2 (new behaviour): asserts the post-change state — prompts MUST
 * enumerate every code in `DEFAULT_MICROS_LIST`; Zod parse of an AI
 * response containing exactly the 30 keys MUST succeed; Zod parse of a
 * response with NO `micros` field must FAIL (the field is required).
 *
 * AC1 surface: every `*_SYSTEM` system instruction string and every
 * `v1_foodParse*` + `v1_visionFoodParse*` payload returned to Gemini must
 * embed the canonical 30 keys verbatim (single-source-of-truth — the
 * prompt text is generated by concatenating the codes from the constant).
 */
import { describe, expect, it } from 'vitest';

import {
  v1_foodParse,
  v1_foodParseVnFallback,
  v1_visionFoodParse,
  v1_visionFoodParseVnFallback,
} from '@/lib/ai/prompts';
import { ParsedItem } from '@/lib/ai/schemas';
import { DEFAULT_MICROS_LIST } from '@/lib/nutrition/micros-rda';

describe('Task C.1 AC1 — all-30-micros-present-in-response', () => {
  it('DEFAULT_MICROS_LIST exposes at least 30 canonical micronutrient codes (briefing §4 AC1)', () => {
    // Single source of truth per design-doc §6 + DT-8. The test asserts
    // length ≥ 30 because briefing §9.7 documents the "30 vs 31" tolerance
    // (the constant IS the source of truth — the test asserts the prompt
    // and the constant stay in sync, not a hardcoded number).
    expect(DEFAULT_MICROS_LIST.length).toBeGreaterThanOrEqual(30);
    // All codes are unique
    const codes = DEFAULT_MICROS_LIST.map((m) => m.code);
    expect(new Set(codes).size).toBe(codes.length);
    // Every entry has the canonical shape `{ code, name, rda, unit }` with
    // a positive RDA (no nullable RDA per architecture spec §2 invariant).
    for (const entry of DEFAULT_MICROS_LIST) {
      expect(typeof entry.code).toBe('string');
      expect(entry.code.length).toBeGreaterThan(0);
      expect(typeof entry.name).toBe('string');
      expect(entry.name.length).toBeGreaterThan(0);
      expect(typeof entry.rda).toBe('number');
      expect(entry.rda).toBeGreaterThan(0);
      expect(typeof entry.unit).toBe('string');
      expect(entry.unit.length).toBeGreaterThan(0);
    }
  });

  it('text-parse system prompt enumerates every DEFAULT_MICROS_LIST code', () => {
    const payload = v1_foodParse({ userText: 'two boiled eggs' });
    const systemPart = payload.systemInstruction.parts[0];
    const systemText = systemPart && 'text' in systemPart ? systemPart.text : '';
    expect(systemText.length).toBeGreaterThan(0);
    for (const entry of DEFAULT_MICROS_LIST) {
      expect(systemText).toContain(entry.code);
    }
  });

  it('text-parse prompt forbids using all-zero micronutrients as an unknown-data shortcut', () => {
    const payload = v1_foodParse({ userText: 'sajtos tejfolos langos fokhagymaval' });
    const systemPart = payload.systemInstruction.parts[0];
    const systemText = systemPart && 'text' in systemPart ? systemPart.text : '';

    expect(systemText).toMatch(/unknown.*zero|zero.*unknown/i);
    expect(systemText).toMatch(/all-zero|all zero/i);
    expect(systemText).toMatch(/mixed food|substantial food/i);
    expect(systemText).toMatch(/ingredient/i);
  });

  it('vision system prompt enumerates every DEFAULT_MICROS_LIST code', () => {
    const payload = v1_visionFoodParse({
      userText: 'a plate of food',
      imageBase64: 'AAAA',
    });
    const systemPart = payload.systemInstruction.parts[0];
    const systemText = systemPart && 'text' in systemPart ? systemPart.text : '';
    expect(systemText.length).toBeGreaterThan(0);
    for (const entry of DEFAULT_MICROS_LIST) {
      expect(systemText).toContain(entry.code);
    }
  });

  it('VN fallback prompts inherit the 30-key directive (single source of truth)', () => {
    const textPayload = v1_foodParseVnFallback({ userText: 'phở bò' });
    const visionPayload = v1_visionFoodParseVnFallback({
      userText: 'phở bò photo',
      imageBase64: 'AAAA',
    });
    const textPart = textPayload.systemInstruction.parts[0];
    const visionPart = visionPayload.systemInstruction.parts[0];
    const textSystem = textPart && 'text' in textPart ? textPart.text : '';
    const visionSystem = visionPart && 'text' in visionPart ? visionPart.text : '';
    for (const entry of DEFAULT_MICROS_LIST) {
      expect(textSystem).toContain(entry.code);
      expect(visionSystem).toContain(entry.code);
    }
  });

  it('ParsedItem Zod schema accepts a micros object containing every DEFAULT_MICROS_LIST key', () => {
    const microsResponse: Record<string, number> = {};
    for (const entry of DEFAULT_MICROS_LIST) {
      microsResponse[entry.code] = 0;
    }
    const aiResponse = {
      name: 'eggs',
      portion: 2,
      unit: 'piece',
      kcal: 140,
      macros: { protein_g: 12, carbs_g: 1, fat_g: 10, fiber_g: 0 },
      micros: microsResponse,
      confidence: 0.9,
    };
    const result = ParsedItem.safeParse(aiResponse);
    expect(result.success).toBe(true);
    if (result.success) {
      // Round-trip preserves every key (no Zod stripping)
      const parsedKeys = Object.keys(result.data.micros).sort();
      const expectedKeys = DEFAULT_MICROS_LIST.map((m) => m.code).sort();
      expect(parsedKeys).toEqual(expectedKeys);
    }
  });

  it('ParsedItem Zod schema rejects a response with no micros field (field is required)', () => {
    const aiResponse = {
      name: 'eggs',
      portion: 2,
      unit: 'piece',
      kcal: 140,
      macros: { protein_g: 12, carbs_g: 1, fat_g: 10, fiber_g: 0 },
      // micros missing
      confidence: 0.9,
    };
    const result = ParsedItem.safeParse(aiResponse);
    expect(result.success).toBe(false);
  });
});

/**
 * Task C.1 — Codex Round 1 Finding 2 regression.
 *
 * The previous prompt put the long `MICROS_DIRECTIVE` BETWEEN the JSON
 * shape exemplar's `macros` and `confidence` lines, which made the
 * exemplar malformed (no trailing comma, free prose mid-object). Under
 * Gemini drift the model could read the directive as a continuation of
 * `"confidence"`. The fix splits the exemplar (valid JSON-like shape)
 * from the directive (separate prose below the block).
 *
 * The tests below assert the exemplar shape is well-formed at the prompt-
 * string level — no free-prose injection inside the `{ … }` block,
 * `confidence` line is comma-preceded, and `MICROS_DIRECTIVE` content
 * does NOT appear inside the JSON exemplar braces.
 */
describe('Task C.1 Codex R1 Finding 2 — JSON exemplar shape integrity', () => {
  function getSystemText(payload: ReturnType<typeof v1_foodParse>): string {
    const part = payload.systemInstruction.parts[0];
    return part && 'text' in part ? part.text : '';
  }

  it('text-parse system prompt micros line in JSON exemplar is a valid JSON-shape placeholder, NOT a free-prose directive', () => {
    const system = getSystemText(v1_foodParse({ userText: 'eggs on toast' }));

    // The JSON exemplar block contains a `"micros":` line. It must be
    // comma-terminated (valid JSON-like) and must NOT carry the long
    // canonical-keys enumeration inline (which was the malformed state).
    const microsLineMatch = system.match(/"micros":\s*\{[^}]*\}\s*,/);
    expect(microsLineMatch).not.toBeNull();

    // The exemplar's `confidence` line MUST be comma-preceded with a real
    // shape line above it (not free prose).
    expect(system).toContain('"confidence": number in [0, 1]');
  });

  it('Codex R2 MEDIUM 3 — JSON exemplar contains NO JS-style comments (`/* */` or `//`)', () => {
    const system = getSystemText(v1_foodParse({ userText: 'eggs on toast' }));

    // JSON does not allow comments. Round-1's fix used `"micros": { /* see ... */ }`
    // which broke the exemplar contract. Assert NEITHER comment style appears
    // anywhere in the assembled prompt.
    expect(system).not.toMatch(/\/\*[\s\S]*?\*\//);
    expect(system).not.toMatch(/(^|[^:\w])\/\//);
  });

  it('Codex R2 MEDIUM 3 — micros line in JSON exemplar parses as valid JSON when extracted', () => {
    const system = getSystemText(v1_foodParse({ userText: 'eggs on toast' }));

    // Capture the inline `"micros": { ... }` object literal from the exemplar.
    const match = system.match(/"micros":\s*(\{[^}]*\})/);
    expect(match).not.toBeNull();
    const microsLiteral = match?.[1] ?? '';

    // Wrap in an outer object so the substring is a complete JSON document,
    // then parse it. Throws if the exemplar contains comments / unquoted
    // identifiers / trailing-comma syntax errors.
    const wrapped = `{ "micros": ${microsLiteral} }`;
    const parsed = JSON.parse(wrapped) as { micros: Record<string, number> };
    expect(parsed.micros).toBeDefined();
    // Every value in the exemplar should be a number (illustrative concrete
    // values per the contract).
    for (const v of Object.values(parsed.micros)) {
      expect(typeof v).toBe('number');
    }
    // The exemplar uses a small subset of canonical keys (2-3 worked
    // examples) — full enumeration lives in the directive paragraph.
    const keys = Object.keys(parsed.micros);
    expect(keys.length).toBeGreaterThanOrEqual(2);
    expect(keys.length).toBeLessThanOrEqual(5);
    // Every shown key must be a canonical code.
    const canonical = new Set<string>(DEFAULT_MICROS_LIST.map((m) => m.code));
    for (const k of keys) {
      expect(canonical.has(k)).toBe(true);
    }
  });

  it('full 30-canonical-keys directive lives OUTSIDE the JSON exemplar braces', () => {
    const system = getSystemText(v1_foodParse({ userText: 'eggs on toast' }));

    // Find the JSON shape exemplar block (between "with this shape:" and
    // the "Micros contract:" header that starts the directive paragraph).
    const shapeStartIdx = system.indexOf('Return a JSON object with this shape:');
    const shapeEndIdx = system.indexOf('Micros contract:');
    expect(shapeStartIdx).toBeGreaterThan(-1);
    expect(shapeEndIdx).toBeGreaterThan(shapeStartIdx);

    const shapeBlock = system.slice(shapeStartIdx, shapeEndIdx);
    // The exemplar carries a SMALL number of illustrative canonical keys
    // (Codex R2 MEDIUM 3 — JSON-valid sample, no comments). The FULL
    // 30-key enumeration must still live BELOW the shape block, not inline.
    // We assert this by checking codes outside the small illustrative set
    // are absent from the shape block, and present in the directive.
    expect(shapeBlock).not.toContain('"choline"');
    expect(shapeBlock).not.toContain('"vitamin_d"');
    expect(shapeBlock).not.toContain('"manganese"');

    // The directive paragraph BELOW the shape block must enumerate every
    // canonical code, including the ones explicitly absent from the shape.
    const directiveBlock = system.slice(shapeEndIdx);
    expect(directiveBlock).toContain('"vitamin_c"');
    expect(directiveBlock).toContain('"vitamin_d"');
    expect(directiveBlock).toContain('"choline"');
    expect(directiveBlock).toContain('"manganese"');
  });

  it('vision system prompt also places the directive OUTSIDE any JSON shape block', () => {
    const payload = v1_visionFoodParse({
      userText: 'a plate of food',
      imageBase64: 'AAAA',
    });
    const part = payload.systemInstruction.parts[0];
    const system = part && 'text' in part ? part.text : '';
    // Vision prompt does not have a JSON shape exemplar — it references
    // text-parse's shape. The directive is a standalone "Micros contract:"
    // paragraph. Verify the directive is its own paragraph (no mid-object
    // injection).
    expect(system).toContain('Micros contract:');
    // The canonical keys must appear AFTER the "Micros contract:" marker.
    const contractIdx = system.indexOf('Micros contract:');
    const vcIdx = system.indexOf('"vitamin_c"');
    expect(contractIdx).toBeGreaterThan(-1);
    expect(vcIdx).toBeGreaterThan(contractIdx);
  });
});

/**
 * Task C.1 — Codex Round 1 Finding 3 regression.
 *
 * Hardened the runtime Zod schema for `micros`:
 *   - reject negative or non-finite numbers
 *   - reject unknown keys (outside DEFAULT_MICROS_LIST)
 *   - allow missing canonical keys but TRANSFORM-fill them with 0
 *
 * Round-trip invariant: fully-populated 30-key response → output has
 * EXACTLY the 30 canonical codes as keys.
 */
describe('Task C.1 Codex R1 Finding 3 — hardened ParsedItem micros schema', () => {
  function withMicros(micros: Record<string, number>) {
    return {
      name: 'eggs',
      portion: 2,
      unit: 'piece',
      kcal: 140,
      macros: { protein_g: 12, carbs_g: 1, fat_g: 10, fiber_g: 0 },
      micros,
      confidence: 0.9,
    };
  }

  function allZeros(): Record<string, number> {
    const out: Record<string, number> = {};
    for (const entry of DEFAULT_MICROS_LIST) out[entry.code] = 0;
    return out;
  }

  it('rejects negative micronutrient values', () => {
    const result = ParsedItem.safeParse(withMicros({ ...allZeros(), vitamin_c: -10 }));
    expect(result.success).toBe(false);
  });

  it('rejects NaN micronutrient values', () => {
    const result = ParsedItem.safeParse(withMicros({ ...allZeros(), iron: Number.NaN }));
    expect(result.success).toBe(false);
  });

  it('rejects Infinity micronutrient values', () => {
    const result = ParsedItem.safeParse(
      withMicros({ ...allZeros(), magnesium: Number.POSITIVE_INFINITY }),
    );
    expect(result.success).toBe(false);
  });

  it('rejects unknown micros keys outside DEFAULT_MICROS_LIST', () => {
    const result = ParsedItem.safeParse(withMicros({ ...allZeros(), made_up_micro: 100 }));
    expect(result.success).toBe(false);
  });

  it('fills missing canonical keys with 0 (round-trip yields exactly 30 keys)', () => {
    // Send only ONE key — Zod fills the rest.
    const result = ParsedItem.safeParse(withMicros({ vitamin_c: 50 }));
    expect(result.success).toBe(true);
    if (result.success) {
      const parsedKeys = Object.keys(result.data.micros).sort();
      const expectedKeys = DEFAULT_MICROS_LIST.map((m) => m.code).sort();
      expect(parsedKeys).toEqual(expectedKeys);
      expect(result.data.micros.vitamin_c).toBe(50);
      expect(result.data.micros.iron).toBe(0);
    }
  });

  it('accepts a fully-populated 30-key response (no extras, no missing)', () => {
    const all = allZeros();
    all.vitamin_c = 90;
    all.iron = 18;
    const result = ParsedItem.safeParse(withMicros(all));
    expect(result.success).toBe(true);
    if (result.success) {
      expect(Object.keys(result.data.micros).sort()).toEqual(
        DEFAULT_MICROS_LIST.map((m) => m.code).sort(),
      );
      expect(result.data.micros.vitamin_c).toBe(90);
      expect(result.data.micros.iron).toBe(18);
    }
  });

  it('accepts zero values for every canonical key', () => {
    const result = ParsedItem.safeParse(withMicros(allZeros()));
    expect(result.success).toBe(true);
  });
});
