/**
 * Task 5.1.1 — Offline outbox queue manager (I11 contract owner + R1 8th consumer).
 *
 * What this module owns
 * ─────────────────────
 * 1. **I11 idempotency contract.** Every retry of an outbox row sends the
 *    SAME serialised body bytes — `client_id` is set ONCE at enqueue, NEVER
 *    regenerated by flush. The server's `UNIQUE(client_id)` index then dedups
 *    duplicate POSTs caused by lost responses.
 *
 * 2. **R1 refresh-interceptor wiring.** Every per-row send routes through
 *    `authFetch` from `@/lib/auth/refresh-interceptor`. There is ZERO raw
 *    `fetch(` in `lib/offline/**`. An ESLint rule (registered in
 *    `eslint.config.mjs`) is the live enforcement; the integration test
 *    `tests/integration/offline-outbox-replay-idempotency.test.ts` is the
 *    belt-and-braces double-check.
 *
 * 3. **Cross-tab race protection.** A `outbox:flush-lock` IDB key with a
 *    5-second TTL prevents two tabs from flushing the same FIFO concurrently.
 *    Lock acquisition is best-effort (read → check TTL → write); two tabs
 *    that race past the read might both grab the lock, but server-side
 *    `UNIQUE(client_id)` dedup means the worst case is 200 + existing-row on
 *    the second tab's request, which is the correct outcome anyway.
 *
 * 4. **Capacity guard at 200 rows.** On enqueue at limit, the OLDEST row is
 *    trimmed (Sentry breadcrumb `outbox.capacity.trim`, no exception). 200
 *    fits comfortably under reasonable IDB quota (~100 KB worst-case for
 *    library payloads); beyond this we treat additional offline activity as
 *    out-of-scope for the MVP.
 *
 * 5. **Sentry policy (errors-only mode).**
 *      Breadcrumbs: enqueue, capacity.trim, flush.start, flush.end.
 *      Exceptions: persistent_failure (≥3 attempts on same row),
 *                  idb.transaction_error (IDB write fails post-availability),
 *                  fatal_drift (body shape parse fails on read).
 *      Routine 4xx/network errors are NOT captured — they are part of the
 *      retry loop's normal operating envelope.
 *
 * Replay error policy (per row)
 * ─────────────────────────────
 *   - 2xx              → remove row (success).
 *   - 412              → keep row, do NOT bump attempts; surface as conflict
 *                        for Task 5.1.5 modal (currently recorded as failed
 *                        in FlushResult — UI consumes ConflictError later).
 *   - 401              → opaque to flush. authFetch refreshes + retries once
 *                        internally; if that also 401s, authFetch throws
 *                        SessionExpiredError → flush treats as network error
 *                        (row stays for next online event after sign-in).
 *   - 4xx (other)      → keep row, bump attempts, record lastError.
 *                        attempts >= 3 → Sentry exception.
 *   - 5xx              → same as 4xx-other (transient by default).
 *   - network/timeout  → stop loop, mark this row, defer remaining rows.
 *
 * NOT in scope (deferred to other 5.1.x sub-tasks):
 *   - React hooks / network state provider          → 5.1.3
 *   - SW registration / offline page                → 5.1.2
 *   - F10 conflict modal / replay status badge UI   → 5.1.5
 *
 * @see Planning/.tmp/task-5.1-ui-architecture.md §A–B
 * @see Planning/architecture.md §1.5 (offline outbox flow), §11 (R1 chain)
 */
import * as Sentry from '@sentry/nextjs';
import { z } from 'zod';

import { authFetch, SessionExpiredError } from '@/lib/auth/refresh-interceptor';

import { detectIdbAvailability } from './availability';
import { idbDel, idbGet, idbSet, idbClearAll } from './idb';
import { ConflictError } from './types';

import type { EnqueueInput, EnqueueResult, FlushResult, OutboxRow } from './types';

/**
 * Read-path validator for persisted outbox rows
 * (F-OFFLINE-5.1.1-FATAL-DRIFT-ROW-SHAPE).
 *
 * Mirrors `OutboxRow` (lib/offline/types.ts) field-for-field. The `kind` enum
 * is the canonical set from `OutboxKind`; adding a new mutation kind there
 * REQUIRES adding it here too. The `body` schema enforces the I11 idempotency
 * key contract — every row's body MUST carry a non-empty `client_id`, because
 * the I11 contract guarantees byte-identical retries hinge on that field.
 *
 * `conflict` is intentionally `.nullish().optional()` so legacy rows from a
 * deploy that pre-dates the 5.1.1 conflict-field addition validate cleanly
 * (their parsed shape is functionally equivalent to `null`). Drifted rows
 * are filtered out and grouped by signature; one Sentry exception per
 * unique signature fires per `readOutbox()` call (see `OUTBOX_DRIFT_TAG`).
 */
const OutboxBodySchema = z.object({ client_id: z.string().min(1) }).catchall(z.unknown());

const OutboxRowSchema = z.object({
  id: z.string().min(1),
  client_id: z.string().min(1),
  kind: z.enum([
    'entry-create',
    'entry-delete',
    'water-log',
    'weight-log',
    'library-update',
    'library-bulk-delete',
    'goal-weight-update',
  ]),
  endpoint: z.string().min(1),
  method: z.enum(['POST', 'PATCH', 'DELETE']),
  body: OutboxBodySchema,
  createdAt: z.number(),
  attempts: z.number().int().nonnegative(),
  lastError: z.string().nullable(),
  lastAttemptAt: z.number().nullable(),
  conflict: z.object({ current: z.unknown(), recordedAt: z.number() }).nullable().optional(),
});

/** Sentry tag used for drift captures so dashboards can group / filter. */
const OUTBOX_DRIFT_TAG = 'outbox.fatal_drift';

/** Soft cap on outbox entries. Oldest row trimmed on enqueue at this limit. */
const MAX_OUTBOX_ROWS = 200;

/** Cross-tab flush lock TTL (ms). Stale lock past this is treated as expired. */
const FLUSH_LOCK_TTL_MS = 5000;

/** Persistent-failure threshold — Sentry exception fires at this many attempts. */
const PERSISTENT_FAILURE_THRESHOLD = 3;

/**
 * Module-level in-flight flush promise. Concurrent `flush()` callers in the
 * SAME tab share this promise; cross-tab serialisation is handled by the IDB
 * lock above.
 */
let inFlightFlush: Promise<FlushResult> | null = null;

/**
 * Task 5.1.3 surgical edit — passive emitter surface so the network-state
 * provider can react to outbox mutations without polling. Consumers register
 * via `subscribe(listener)`; outbox internals call `notify()` after every
 * persisted mutation (enqueue / remove / markFailed / recordConflict) and at
 * flush start / end. The emitter is intentionally minimal: no payload is
 * passed, the listener simply re-reads `size()` to refresh state. This keeps
 * the emitter cheap and preserves the I11 contract (no client_id leakage
 * through the notification path).
 */
const subscribers = new Set<() => void>();

function notify(): void {
  // Snapshot the listener set before iterating so a listener that
  // unsubscribes itself synchronously cannot mutate the set mid-iteration.
  for (const listener of Array.from(subscribers)) {
    try {
      listener();
    } catch (err) {
      // Listener errors must not break the outbox path. Surface to Sentry as
      // an info breadcrumb so we can detect noisy consumers without aborting
      // mutations.
      Sentry.addBreadcrumb({
        category: 'outbox',
        level: 'warning',
        message: 'outbox.subscribe.listener_threw',
        data: { error: err instanceof Error ? err.message : String(err) },
      });
    }
  }
}

/**
 * Subscribe to outbox change notifications. Returns an unsubscribe function;
 * calling it more than once is a no-op (idempotent).
 *
 * Listeners receive NO payload — the emitter is a wake-up signal only. The
 * listener re-reads via `size()` / `peek()` to obtain a fresh view. This
 * keeps the I11 contract intact (`client_id` never flows through the
 * notification surface).
 */
export function subscribe(listener: () => void): () => void {
  subscribers.add(listener);
  return () => {
    subscribers.delete(listener);
  };
}

/**
 * Generate a UUID v4 for the IDB row identifier. The body's `client_id` is
 * minted by the caller — this is just the local row id, kept distinct from
 * the I11 idempotency key for clarity.
 */
function newRowId(): string {
  return crypto.randomUUID();
}

function nowMs(): number {
  return Date.now();
}

function emptyFlushResult(idbAvailable: boolean): FlushResult {
  return {
    attempted: 0,
    succeeded: 0,
    failed: [],
    durationMs: 0,
    idbAvailable,
  };
}

/**
 * Read the persisted outbox array. Always returns an array, never `undefined`.
 *
 * Two layers of drift protection:
 *
 *   1. **Top-level guard.** If a stored value parses to a non-array
 *      (post-deploy schema regression), capture one exception and reset to
 *      `[]`. The user keeps operating; the corrupt blob is discarded.
 *
 *   2. **Per-row Zod validator** (F-OFFLINE-5.1.1-FATAL-DRIFT-ROW-SHAPE).
 *      Each row is parsed against `OutboxRowSchema`. Rows that fail are
 *      dropped from the returned array — they would otherwise blow up
 *      downstream `JSON.stringify` / `authFetch` paths with generic errors.
 *      Failing rows are grouped by a "drift signature" computed from the
 *      Zod issue paths + codes; one Sentry exception fires per unique
 *      signature per call (NOT per failing row), preserving observability
 *      without flooding the Sentry queue when a deploy invalidates many
 *      rows at once. The Sentry capture is best-effort: it is wrapped in a
 *      try/catch so a Sentry-internal failure cannot break the read path.
 */
async function readOutbox(): Promise<OutboxRow[]> {
  const raw = await idbGet('outbox');
  if (raw === undefined) return [];
  if (!Array.isArray(raw)) {
    Sentry.captureException(new Error('outbox.fatal_drift: stored outbox is not an array'), {
      tags: { component: 'offline-outbox', op: 'read' },
    });
    // Reset to a clean state so the user can keep operating.
    await idbSet('outbox', []);
    return [];
  }

  const valid: OutboxRow[] = [];
  const driftCounts = new Map<string, number>();

  for (const candidate of raw) {
    const parsed = OutboxRowSchema.safeParse(candidate);
    if (parsed.success) {
      valid.push(parsed.data as OutboxRow);
      continue;
    }
    // Compose a stable, sorted signature from the failed-issue paths + codes
    // so two rows broken the same way collapse into one Sentry capture, while
    // genuinely different breakages remain distinguishable.
    const signature = parsed.error.issues
      .map((issue) => `${issue.path.join('.') || '<root>'}:${issue.code}`)
      .sort()
      .join('|');
    driftCounts.set(signature, (driftCounts.get(signature) ?? 0) + 1);
  }

  if (driftCounts.size > 0) {
    for (const [signature, count] of driftCounts) {
      try {
        Sentry.captureException(new Error('outbox.fatal_drift: row shape parse failed'), {
          tags: { component: 'offline-outbox', op: 'read', [OUTBOX_DRIFT_TAG]: 'true' },
          extra: { signature, count },
        });
      } catch {
        // Best-effort: Sentry is errors-only and may no-op in environments
        // where it isn't loaded. Swallowing here keeps the read path resilient.
      }
    }
  }

  return valid;
}

/**
 * Write the outbox back. Returns true on success, false on IDB transaction
 * failure (in which case a Sentry exception is captured). Callers SHOULD
 * propagate the false return so user-visible state stays consistent with
 * persisted state — a "succeeded" flush row that failed to delete from IDB
 * will get retried on the next flush, but the user-facing FlushResult must
 * not pretend the write happened.
 */
async function writeOutbox(rows: OutboxRow[], op: string): Promise<boolean> {
  const ok = await idbSet('outbox', rows);
  if (!ok) {
    Sentry.captureException(new Error(`outbox.idb.transaction_error: ${op}`), {
      tags: { component: 'offline-outbox', op },
    });
  }
  return ok;
}

/**
 * Enqueue a mutation. The body MUST already carry `client_id` — see I11
 * contract notes at the top of this file.
 */
export async function enqueue(input: EnqueueInput): Promise<EnqueueResult> {
  if (typeof input.body?.client_id !== 'string' || input.body.client_id.length === 0) {
    // Programmer error — caller forgot to mint client_id before optimistic UI.
    // We DO NOT silently invent one here because the caller's optimistic UI
    // already references some id, and minting a different one inside the
    // outbox would let the optimistic state and the persisted row diverge.
    throw new Error('outbox.enqueue: body.client_id is required (I11 contract violation)');
  }

  const id = newRowId();
  const row: OutboxRow = {
    id,
    client_id: input.body.client_id,
    kind: input.kind,
    endpoint: input.endpoint,
    method: input.method,
    body: input.body,
    createdAt: nowMs(),
    attempts: 0,
    lastError: null,
    lastAttemptAt: null,
    conflict: null,
  };

  // IDB-availability gate: if the platform doesn't support persistent storage
  // we short-circuit BEFORE building the next-state array so the caller's
  // toast surfaces immediately.
  const availability = await detectIdbAvailability();
  if (!availability.ok) {
    return { id, client_id: input.body.client_id, idbAvailable: false };
  }

  const before = await readOutbox();
  let next = [...before, row];

  // Capacity guard — applied AFTER append so we can detect the at-limit case.
  if (next.length > MAX_OUTBOX_ROWS) {
    const trimCount = next.length - MAX_OUTBOX_ROWS;
    const trimmed = next.slice(0, trimCount);
    next = next.slice(trimCount);
    for (const trimmedRow of trimmed) {
      Sentry.addBreadcrumb({
        category: 'outbox',
        level: 'warning',
        message: 'outbox.capacity.trim',
        data: { kind: trimmedRow.kind, ageMs: nowMs() - trimmedRow.createdAt },
      });
    }
  }

  // Route through writeOutbox so a transaction error is captured uniformly
  // (Codex review I3 — observability gap on enqueue write fail).
  const writeOk = await writeOutbox(next, 'enqueue');
  if (!writeOk) {
    return { id, client_id: input.body.client_id, idbAvailable: false };
  }

  Sentry.addBreadcrumb({
    category: 'outbox',
    level: 'info',
    message: 'outbox.enqueue',
    data: { kind: input.kind, queueSize: next.length },
  });

  notify();
  return { id, client_id: input.body.client_id, idbAvailable: true };
}

/**
 * Peek the FIFO queue. Returns oldest-first by `createdAt` ascending.
 * Optional `limit` truncates the result.
 */
export async function peek(limit?: number): Promise<OutboxRow[]> {
  const rows = await readOutbox();
  const sorted = [...rows].sort((a, b) => a.createdAt - b.createdAt);
  return typeof limit === 'number' ? sorted.slice(0, limit) : sorted;
}

/** Number of rows currently queued. Returns 0 when IDB is unavailable. */
export async function size(): Promise<number> {
  const rows = await readOutbox();
  return rows.length;
}

/**
 * Remove a row by `client_id`. Returns true on a real removal (write
 * persisted), false otherwise (either absent or IDB transaction failure).
 * Callers MUST honour the return value when deciding whether to mark a
 * flush row as "succeeded" — a 200 response that fails to delete from IDB
 * means the row will be sent again on the next flush, and the user-facing
 * tally must reflect the persisted truth.
 */
export async function remove(client_id: string): Promise<boolean> {
  const rows = await readOutbox();
  const next = rows.filter((r) => r.client_id !== client_id);
  if (next.length === rows.length) return false; // not found
  const ok = await writeOutbox(next, 'remove');
  if (ok) notify();
  return ok;
}

/**
 * Mark a row as failed. Increments `attempts` + records `lastError`.
 * Returns true when the write persisted, false otherwise.
 */
export async function markFailed(client_id: string, error: string): Promise<boolean> {
  const rows = await readOutbox();
  const idx = rows.findIndex((r) => r.client_id === client_id);
  if (idx < 0) return false;
  const updated = rows.slice();
  const original = updated[idx];
  if (!original) return false;
  updated[idx] = {
    ...original,
    attempts: original.attempts + 1,
    lastError: error,
    lastAttemptAt: nowMs(),
  };
  const ok = await writeOutbox(updated, 'markFailed');
  if (ok) notify();
  return ok;
}

/**
 * 412 conflict path — records the error AND the server's `current` value on
 * the row WITHOUT bumping `attempts`. Persistent_failure must not fire on a
 * user-prompt path. Task 5.1.5's modal reads `row.conflict.current` to render
 * the conflict UI.
 */
async function recordConflict(
  client_id: string,
  error: string,
  current: unknown,
): Promise<boolean> {
  const rows = await readOutbox();
  const idx = rows.findIndex((r) => r.client_id === client_id);
  if (idx < 0) return false;
  const updated = rows.slice();
  const original = updated[idx];
  if (!original) return false;
  updated[idx] = {
    ...original,
    lastError: error,
    lastAttemptAt: nowMs(),
    conflict: { current, recordedAt: nowMs() },
  };
  const ok = await writeOutbox(updated, 'recordConflict');
  if (ok) notify();
  return ok;
}

/**
 * Production-gated wipe. Throws when `NEXT_PUBLIC_KALORI_ENV === 'production'`.
 * Used by dev tooling + tests; never call from production UI.
 */
export async function clear(): Promise<void> {
  if (process.env.NEXT_PUBLIC_KALORI_ENV === 'production') {
    throw new Error('outbox.clear: forbidden in production');
  }
  await idbClearAll();
}

/**
 * Try to acquire the cross-tab flush lock. Returns the owner UUID on success,
 * `null` if a fresh (≤ TTL) lock is already held by another tab.
 *
 * Best-effort: two tabs that race the read might both pass the staleness
 * check. The server's `UNIQUE(client_id)` dedup makes that safe — the worst
 * case is the second tab's POSTs return 200 + existing-row (I11 "replayed"
 * semantics). Per-call owner UUID prevents Tab A's `finally`-release from
 * deleting a newer lock acquired by Tab B after A's TTL expired (Codex
 * review I2).
 */
async function acquireFlushLock(): Promise<string | null> {
  const existing = await idbGet('outbox:flush-lock');
  if (existing && typeof existing.acquiredAt === 'number') {
    const age = nowMs() - existing.acquiredAt;
    if (age >= 0 && age < FLUSH_LOCK_TTL_MS) {
      return null; // fresh lock — another tab is flushing.
    }
  }
  const owner = crypto.randomUUID();
  await idbSet('outbox:flush-lock', { acquiredAt: nowMs(), owner });
  return owner;
}

/**
 * Release the cross-tab flush lock IFF we still own it. If the lock has been
 * stolen by another tab (e.g. our flush exceeded the TTL), we leave it alone
 * so the other tab's release path runs cleanly.
 */
async function releaseFlushLock(owner: string): Promise<void> {
  const current = await idbGet('outbox:flush-lock');
  if (current && (current as { owner?: string }).owner === owner) {
    await idbDel('outbox:flush-lock');
  }
}

/**
 * Flush the outbox. Sends each row through `authFetch` (R1 contract).
 *
 * Concurrency model:
 *   - Same-tab concurrent callers share the in-flight promise (module-level).
 *   - Cross-tab serialised by `outbox:flush-lock` IDB key (5s TTL).
 *   - Per-row serial inside one flush (FIFO order, never parallel) — preserves
 *     cause-effect for chained mutations on the same record.
 */
export async function flush(): Promise<FlushResult> {
  if (inFlightFlush) {
    return inFlightFlush;
  }
  const promise = doFlush();
  inFlightFlush = promise;
  try {
    return await promise;
  } finally {
    inFlightFlush = null;
  }
}

async function doFlush(): Promise<FlushResult> {
  // IDB-availability gate — Safari private mode + missing-indexedDB browsers
  // get a no-op flush. Result is cached inside availability.ts after first
  // probe, so the steady-state cost is one Map lookup.
  const availability = await detectIdbAvailability();
  if (!availability.ok) {
    return emptyFlushResult(false);
  }

  const start = nowMs();
  const lockOwner = await acquireFlushLock();
  if (lockOwner === null) {
    return emptyFlushResult(true);
  }

  try {
    const rows = await peek();
    if (rows.length === 0) {
      return { ...emptyFlushResult(true), durationMs: nowMs() - start };
    }

    Sentry.addBreadcrumb({
      category: 'outbox',
      level: 'info',
      message: 'outbox.flush.start',
      data: { queueSize: rows.length },
    });
    notify();

    const result: FlushResult = {
      attempted: 0,
      succeeded: 0,
      failed: [],
      durationMs: 0,
      idbAvailable: true,
    };

    for (const row of rows) {
      result.attempted += 1;
      const stop = await sendRow(row, result);
      if (stop) break; // network error → defer remaining rows.
    }

    result.durationMs = nowMs() - start;

    Sentry.addBreadcrumb({
      category: 'outbox',
      level: 'info',
      message: 'outbox.flush.end',
      data: {
        attempted: result.attempted,
        succeeded: result.succeeded,
        failed: result.failed.length,
        durationMs: result.durationMs,
      },
    });

    notify();
    return result;
  } finally {
    await releaseFlushLock(lockOwner);
  }
}

/**
 * Send one row. Returns `true` if the flush loop should stop (network error
 * defers remaining rows to the next online event).
 */
async function sendRow(row: OutboxRow, result: FlushResult): Promise<boolean> {
  let response: Response;
  try {
    // R1: route through authFetch — NEVER raw fetch.
    // I11: body.client_id is the idempotency key — JSON.stringify produces
    //      identical bytes every retry of this row.
    response = await authFetch(row.endpoint, {
      method: row.method,
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(row.body),
    });
  } catch (err) {
    // SessionExpiredError → user is signed out; row stays for next session.
    // Network/timeout/DNS errors → defer remaining rows.
    const message = err instanceof Error ? err.message : String(err);
    await markFailed(row.client_id, message);
    result.failed.push({ client_id: row.client_id, kind: row.kind, error: message });
    if (err instanceof SessionExpiredError) {
      // Authoritative sign-out — interceptor already redirected. Stop loop.
      return true;
    }
    // Generic network error — stop loop so subsequent rows aren't blasted.
    return true;
  }

  if (response.status >= 200 && response.status < 300) {
    // Only count as succeeded when the IDB delete persists. A failed delete
    // means the row will be sent again on the next flush; reporting "succeeded"
    // would diverge user-visible state from persisted state. Server-side I11
    // dedup means the retry returns 200 + existing-row → safe.
    const removed = await remove(row.client_id);
    if (removed) {
      result.succeeded += 1;
    } else {
      result.failed.push({
        client_id: row.client_id,
        kind: row.kind,
        error: 'idb_remove_failed: row will retry on next flush',
      });
    }
    return false;
  }

  // 412 — F10 conflict path. Keep row, do NOT bump attempts.
  if (response.status === 412) {
    let current: unknown = null;
    try {
      const body = (await response.clone().json()) as { current?: unknown };
      current = body.current ?? null;
    } catch {
      // 412 without parseable body — still surface as conflict (current=null).
    }
    const error = `412 Precondition Failed (${row.kind})`;
    await recordConflict(row.client_id, error, current);
    result.failed.push({
      client_id: row.client_id,
      kind: row.kind,
      error,
      conflict: { current },
    });
    return false;
  }

  // 4xx (other) and 5xx — keep row, bump attempts, possibly capture exception.
  const error = `${response.status} ${response.statusText || ''}`.trim();
  await markFailed(row.client_id, error);
  result.failed.push({ client_id: row.client_id, kind: row.kind, error });

  // After markFailed, re-read the row's attempts to decide on Sentry capture.
  const refreshed = await readOutbox();
  const updated = refreshed.find((r) => r.client_id === row.client_id);
  if (updated && updated.attempts >= PERSISTENT_FAILURE_THRESHOLD) {
    Sentry.captureException(new Error(`outbox.flush.persistent_failure: ${row.kind} ${error}`), {
      tags: {
        component: 'offline-outbox',
        kind: row.kind,
        endpoint: row.endpoint,
      },
    });
  }
  return false;
}

/**
 * Test-only helper to expose the in-flight flush promise. Not exported from
 * any barrel — only `tests/**` should reach for this.
 */
export const __testHelpers = {
  get inFlightFlush(): Promise<FlushResult> | null {
    return inFlightFlush;
  },
  resetInFlight(): void {
    inFlightFlush = null;
  },
  MAX_OUTBOX_ROWS,
  FLUSH_LOCK_TTL_MS,
  PERSISTENT_FAILURE_THRESHOLD,
};

/** Re-export ConflictError so consumers don't need to import from `./types`. */
export { ConflictError };

/** Re-export the kind enum + interfaces for ergonomic consumer imports. */
export type { OutboxKind, OutboxRow, EnqueueInput, EnqueueResult, FlushResult } from './types';
